controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

inventory_save:
    path: /inventory/save
    controller: App\Controller\InventoryController::save